# Site settings
title: GSoC 2022 | Prakarsh Kaushik
description: >-
  Consolidation of drone based <br>
  exercises for Jderobot Robotics Academy <br>
  <b><a href="https://summerofcode.withgoogle.com/programs/2022/projects/RJd3bxAY" target="_blank" rel="noopener">Project #2</a></b> <br>
lang: en-US
timezone: Europe/Berlin
image: /assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/TheRoboticsClub/gsoc2022-Prakarsh_Kaushik
mode: light # default theme "dark" | "light"

# Profile settings
author:
  sitename: Google Summer of Code '22 Blog <br>
  name: Prakarsh Kaushik
  bio: >-
    <b><a href="https://summerofcode.withgoogle.com/programs/2022/projects/RJd3bxAY" target="_blank" rel="noopener">Project #2</a></b> <br>
    Consolidation of drone based <br>
    exercises for Jderobot Robotics Academy <br>
    
    
  username: prakarshkaushik
  email: prakarshkaushik369@gmail.com
  avatar: assets/img/logo.png

# Url settings
url: "https://theroboticsclub.github.io"
baseurl: "/gsoc2022-Prakarsh_Kaushik"
google_analytics: UA-126403543-4
fb_appid:

# Collection setting
collections:
  posts:
    output: true

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  math_engine: mathjax

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:
      
# Build settings
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sass-converter
  - jekyll-sitemap
  - jekyll-postfiles
